# Site settings
title: "Jekyll Resume Template"
description: "A resume template for Jekyll and GitHub Pages sites."

# Build settings
markdown: kramdown
sass:
  sass_dir: _sass
  style: compressed

plugins:
  # previously provided by GitHub Pages legacy deployment
  # see https://docs.github.com/en/pages/setting-up-a-github-pages-site-with-jekyll/about-github-pages-and-jekyll#plugins
  # - jekyll-coffeescript
  # - jekyll-default-layout
  # - jekyll-gist
  # - jekyll-github-metadata
  # - jekyll-optional-front-matter
  # - jekyll-paginate
  # - jekyll-readme-index
  # - jekyll-titles-from-headings
  # - jekyll-relative-links

  - jekyll-avatar
  - jekyll-feed
  - jekyll-remote-theme

  # consider using now with GitHub Actions deployment
  #- jekyll-email-protect
  #- jekyll_github_chart
  #- jekyll-mermaid
  #TODO compare to jemoji
  #- jekyll-octicons

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

# Resume settings
resume_avatar:                  octocat
resume_name:                    "octocat"
resume_title:                   "GitHub's Mascot"

# used for the contact button in _layouts/resume.html
resume_contact_email:           "example@example.com"

resume_header_contact_info:     "Earth • 555-7334 • example@example.com"
display_header_contact_info:    "false"

resume_header_intro: >
  <p>This is the executive summary.
     You should write a few brief, concise, and meaningful sentences
     about yourself from a professional context, and your immediate career goals.
     Make the length appropriate for your needs, but keep it brief and concise</p>

# use "yes" to display the email contact button,
# "no" to display an "I'm not looking for work" message,
# or remove the resume_looking_for_work option entirely
# to leave blank
resume_looking_for_work:        "yes"

# Decide which sections to use
# comment out to hide
resume_section_experience:      true
resume_section_education:       true
resume_section_projects:        true
resume_section_skills:          true
resume_section_recognition:     true
resume_section_links:           true
resume_section_associations:    true
# resume_section_interests:       true

# Resume social links
# uncomment the options you wish to display, and add your own URL
resume_social_links:
  resume_github_url:            "https://github.com/jglovier/resume-template"
  resume_twitter_url:           "http://twitter.com/jglovier"
  resume_dribbble_url:          "https://dribbble.com/jag"
  # resume_facebook_url:          "insert Facebook URL here"
  resume_linkedin_url:          "https://www.linkedin.com/in/joelglovier"
  # resume_instagram_url:         "insert your Instagram URL here"
  resume_website_url:           "http://joelglovier.com"
  resume_medium_url:            "https://medium.com/@jglovier"
resume_print_social_links:      true

# Design settings
resume_theme:                   default

# Note: when editing locally, remember to restart
# your Jekyll server when you edit this file. Changes
# to _config.yml are only recognized when the server starts
